name: todoflutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  sqflite: any
  path_provider: any # for Database Path
  intl: ^0.15.7 # for Date Formate

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

